package com.apptolast.greenhouse.admin.data.remote.api

import com.apptolast.greenhouse.admin.data.model.ActuatorStateCreateRequest
import com.apptolast.greenhouse.admin.data.model.ActuatorStateResponse
import com.apptolast.greenhouse.admin.data.model.ActuatorStateUpdateRequest
import com.apptolast.greenhouse.admin.data.model.AlertSeverityCreateRequest
import com.apptolast.greenhouse.admin.data.model.AlertSeverityResponse
import com.apptolast.greenhouse.admin.data.model.AlertSeverityUpdateRequest
import com.apptolast.greenhouse.admin.data.model.AlertTypeCreateRequest
import com.apptolast.greenhouse.admin.data.model.AlertTypeResponse
import com.apptolast.greenhouse.admin.data.model.AlertTypeUpdateRequest
import com.apptolast.greenhouse.admin.data.model.DeviceCategoryCreateRequest
import com.apptolast.greenhouse.admin.data.model.DeviceCategoryResponse
import com.apptolast.greenhouse.admin.data.model.DeviceCategoryUpdateRequest
import com.apptolast.greenhouse.admin.data.model.DeviceTypeCreateRequest
import com.apptolast.greenhouse.admin.data.model.DeviceTypeResponse
import com.apptolast.greenhouse.admin.data.model.DeviceTypeUpdateRequest
import com.apptolast.greenhouse.admin.data.model.DeviceUnitCreateRequest
import com.apptolast.greenhouse.admin.data.model.DeviceUnitResponse
import com.apptolast.greenhouse.admin.data.model.DeviceUnitUpdateRequest
import com.apptolast.greenhouse.admin.data.model.PeriodCreateRequest
import com.apptolast.greenhouse.admin.data.model.PeriodResponse
import com.apptolast.greenhouse.admin.data.model.PeriodUpdateRequest
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.delete
import io.ktor.client.request.get
import io.ktor.client.request.patch
import io.ktor.client.request.post
import io.ktor.client.request.put
import io.ktor.client.request.setBody

/**
 * API service for catalog CRUD operations.
 * Communicates with the /catalog/ * endpoints of InvernaderosAPI.
 * Note: Paths are relative (no leading slash) to append to base URL.
 *
 * Catalog endpoints are global (not tenant-specific) and manage:
 * - Device Categories (Sensor, Actuator)
 * - Device Types (Temperature, Humidity, etc.)
 * - Device Units (°C, %, etc.) - READ ONLY
 * - Alert Types (Manual, Automatic, System, etc.)
 * - Alert Severities (Info, Warning, Critical, etc.)
 * - Periods (Day, Night, All)
 */
class CatalogApiService(private val httpClient: HttpClient) {

    // ==================== DEVICE CATEGORIES ====================

    /**
     * Get all device categories from the catalog.
     */
    suspend fun getDeviceCategories(): List<DeviceCategoryResponse> {
        return httpClient.get("catalog/device-categories").body()
    }

    /**
     * Get a specific device category by ID.
     */
    suspend fun getDeviceCategory(id: Short): DeviceCategoryResponse {
        return httpClient.get("catalog/device-categories/$id").body()
    }

    /**
     * Create a new device category.
     * Note: ID must be provided in the request.
     */
    suspend fun createDeviceCategory(request: DeviceCategoryCreateRequest): DeviceCategoryResponse {
        return httpClient.post("catalog/device-categories") {
            setBody(request)
        }.body()
    }

    /**
     * Update an existing device category.
     */
    suspend fun updateDeviceCategory(id: Short, request: DeviceCategoryUpdateRequest): DeviceCategoryResponse {
        return httpClient.put("catalog/device-categories/$id") {
            setBody(request)
        }.body()
    }

    /**
     * Delete a device category.
     */
    suspend fun deleteDeviceCategory(id: Short) {
        httpClient.delete("catalog/device-categories/$id")
    }

    // ==================== DEVICE TYPES ====================

    /**
     * Get all device types from the catalog.
     */
    suspend fun getDeviceTypes(): List<DeviceTypeResponse> {
        return httpClient.get("catalog/device-types").body()
    }

    /**
     * Get device types filtered by category.
     */
    suspend fun getDeviceTypesByCategory(categoryId: Short): List<DeviceTypeResponse> {
        return httpClient.get("catalog/device-types?categoryId=$categoryId").body()
    }

    /**
     * Get a specific device type by ID.
     */
    suspend fun getDeviceType(id: Short): DeviceTypeResponse {
        return httpClient.get("catalog/device-types/$id").body()
    }

    /**
     * Create a new device type.
     * Note: ID is auto-generated by the backend.
     */
    suspend fun createDeviceType(request: DeviceTypeCreateRequest): DeviceTypeResponse {
        return httpClient.post("catalog/device-types") {
            setBody(request)
        }.body()
    }

    /**
     * Update an existing device type.
     */
    suspend fun updateDeviceType(id: Short, request: DeviceTypeUpdateRequest): DeviceTypeResponse {
        return httpClient.put("catalog/device-types/$id") {
            setBody(request)
        }.body()
    }

    /**
     * Delete a device type.
     */
    suspend fun deleteDeviceType(id: Short) {
        httpClient.delete("catalog/device-types/$id")
    }

    /**
     * Activate a device type.
     */
    suspend fun activateDeviceType(id: Short): DeviceTypeResponse {
        return httpClient.post("catalog/device-types/$id/activate").body()
    }

    /**
     * Deactivate a device type.
     */
    suspend fun deactivateDeviceType(id: Short): DeviceTypeResponse {
        return httpClient.post("catalog/device-types/$id/deactivate").body()
    }

    // ==================== DEVICE UNITS ====================

    /**
     * Get all device units from the catalog.
     */
    suspend fun getDeviceUnits(): List<DeviceUnitResponse> {
        return httpClient.get("catalog/units").body()
    }

    /**
     * Get a specific device unit by ID.
     */
    suspend fun getDeviceUnit(id: Short): DeviceUnitResponse {
        return httpClient.get("catalog/units/$id").body()
    }

    /**
     * Create a new device unit.
     * Note: ID is auto-generated by the backend.
     */
    suspend fun createDeviceUnit(request: DeviceUnitCreateRequest): DeviceUnitResponse {
        return httpClient.post("catalog/units") {
            setBody(request)
        }.body()
    }

    /**
     * Update an existing device unit.
     */
    suspend fun updateDeviceUnit(id: Short, request: DeviceUnitUpdateRequest): DeviceUnitResponse {
        return httpClient.put("catalog/units/$id") {
            setBody(request)
        }.body()
    }

    /**
     * Delete a device unit.
     */
    suspend fun deleteDeviceUnit(id: Short) {
        httpClient.delete("catalog/units/$id")
    }

    /**
     * Activate a device unit.
     */
    suspend fun activateDeviceUnit(id: Short): DeviceUnitResponse {
        return httpClient.patch("catalog/units/$id/activate").body()
    }

    /**
     * Deactivate a device unit.
     */
    suspend fun deactivateDeviceUnit(id: Short): DeviceUnitResponse {
        return httpClient.patch("catalog/units/$id/deactivate").body()
    }

    // ==================== ALERT TYPES ====================

    /**
     * Get all alert types from the catalog.
     */
    suspend fun getAlertTypes(): List<AlertTypeResponse> {
        return httpClient.get("catalog/alert-types").body()
    }

    /**
     * Get a specific alert type by ID.
     */
    suspend fun getAlertType(id: Short): AlertTypeResponse {
        return httpClient.get("catalog/alert-types/$id").body()
    }

    /**
     * Create a new alert type.
     * Note: ID must be provided in the request.
     */
    suspend fun createAlertType(request: AlertTypeCreateRequest): AlertTypeResponse {
        return httpClient.post("catalog/alert-types") {
            setBody(request)
        }.body()
    }

    /**
     * Update an existing alert type.
     */
    suspend fun updateAlertType(id: Short, request: AlertTypeUpdateRequest): AlertTypeResponse {
        return httpClient.put("catalog/alert-types/$id") {
            setBody(request)
        }.body()
    }

    /**
     * Delete an alert type.
     */
    suspend fun deleteAlertType(id: Short) {
        httpClient.delete("catalog/alert-types/$id")
    }

    // ==================== ALERT SEVERITIES ====================

    /**
     * Get all alert severities from the catalog.
     */
    suspend fun getAlertSeverities(): List<AlertSeverityResponse> {
        return httpClient.get("catalog/alert-severities").body()
    }

    /**
     * Get a specific alert severity by ID.
     */
    suspend fun getAlertSeverity(id: Short): AlertSeverityResponse {
        return httpClient.get("catalog/alert-severities/$id").body()
    }

    /**
     * Create a new alert severity.
     * Note: ID must be provided in the request.
     */
    suspend fun createAlertSeverity(request: AlertSeverityCreateRequest): AlertSeverityResponse {
        return httpClient.post("catalog/alert-severities") {
            setBody(request)
        }.body()
    }

    /**
     * Update an existing alert severity.
     */
    suspend fun updateAlertSeverity(id: Short, request: AlertSeverityUpdateRequest): AlertSeverityResponse {
        return httpClient.put("catalog/alert-severities/$id") {
            setBody(request)
        }.body()
    }

    /**
     * Delete an alert severity.
     */
    suspend fun deleteAlertSeverity(id: Short) {
        httpClient.delete("catalog/alert-severities/$id")
    }

    // ==================== PERIODS ====================

    /**
     * Get all periods from the catalog.
     */
    suspend fun getPeriods(): List<PeriodResponse> {
        return httpClient.get("catalog/periods").body()
    }

    /**
     * Get a specific period by ID.
     */
    suspend fun getPeriod(id: Short): PeriodResponse {
        return httpClient.get("catalog/periods/$id").body()
    }

    /**
     * Create a new period.
     * Note: ID must be provided in the request.
     */
    suspend fun createPeriod(request: PeriodCreateRequest): PeriodResponse {
        return httpClient.post("catalog/periods") {
            setBody(request)
        }.body()
    }

    /**
     * Update an existing period.
     */
    suspend fun updatePeriod(id: Short, request: PeriodUpdateRequest): PeriodResponse {
        return httpClient.put("catalog/periods/$id") {
            setBody(request)
        }.body()
    }

    /**
     * Delete a period.
     */
    suspend fun deletePeriod(id: Short) {
        httpClient.delete("catalog/periods/$id")
    }

    // ==================== ACTUATOR STATES ====================

    /**
     * Get all actuator states from the catalog.
     */
    suspend fun getActuatorStates(): List<ActuatorStateResponse> {
        return httpClient.get("catalog/actuator-states").body()
    }

    /**
     * Get only operational actuator states.
     */
    suspend fun getOperationalActuatorStates(): List<ActuatorStateResponse> {
        return httpClient.get("catalog/actuator-states/operational").body()
    }

    /**
     * Get a specific actuator state by ID.
     */
    suspend fun getActuatorState(id: Short): ActuatorStateResponse {
        return httpClient.get("catalog/actuator-states/$id").body()
    }

    /**
     * Create a new actuator state.
     * Note: ID is auto-generated by the backend.
     */
    suspend fun createActuatorState(request: ActuatorStateCreateRequest): ActuatorStateResponse {
        return httpClient.post("catalog/actuator-states") {
            setBody(request)
        }.body()
    }

    /**
     * Update an existing actuator state.
     */
    suspend fun updateActuatorState(id: Short, request: ActuatorStateUpdateRequest): ActuatorStateResponse {
        return httpClient.put("catalog/actuator-states/$id") {
            setBody(request)
        }.body()
    }

    /**
     * Delete an actuator state.
     */
    suspend fun deleteActuatorState(id: Short) {
        httpClient.delete("catalog/actuator-states/$id")
    }
}