package com.apptolast.greenhouse.admin.domain.repository

import com.apptolast.greenhouse.admin.data.model.AlertSeverityCatalog
import com.apptolast.greenhouse.admin.data.model.AlertType
import com.apptolast.greenhouse.admin.data.model.DeviceCatalogCategory
import com.apptolast.greenhouse.admin.data.model.DeviceCatalogType
import com.apptolast.greenhouse.admin.data.model.DeviceCatalogUnit
import com.apptolast.greenhouse.admin.data.model.Period

/**
 * Repository interface for catalog CRUD operations.
 * Catalogs are global (not tenant-specific) configuration data used in dropdowns.
 * All methods return Result<T> for consistent error handling.
 */
interface CatalogRepository {

    // ==================== DEVICE CATEGORIES ====================

    /**
     * Fetches all device categories from the catalog.
     * @return Result containing list of DeviceCatalogCategory or error
     */
    suspend fun getDeviceCategories(): Result<List<DeviceCatalogCategory>>

    /**
     * Creates a new device category.
     * @param name The category name
     * @return Result containing the created DeviceCatalogCategory or error
     */
    suspend fun createDeviceCategory(name: String): Result<DeviceCatalogCategory>

    /**
     * Updates an existing device category.
     * @param id The category ID to update
     * @param name The new category name
     * @return Result containing the updated DeviceCatalogCategory or error
     */
    suspend fun updateDeviceCategory(id: Short, name: String): Result<DeviceCatalogCategory>

    /**
     * Deletes a device category.
     * @param id The category ID to delete
     * @return Result containing success or error
     */
    suspend fun deleteDeviceCategory(id: Short): Result<Unit>

    // ==================== DEVICE TYPES ====================

    /**
     * Fetches all device types from the catalog.
     * @return Result containing list of DeviceCatalogType or error
     */
    suspend fun getDeviceTypes(): Result<List<DeviceCatalogType>>

    /**
     * Creates a new device type.
     * Note: ID is auto-generated by the backend.
     * @param name The type name
     * @param description Optional description
     * @param categoryId The category this type belongs to
     * @param defaultUnitId Optional default unit ID
     * @param dataType Optional data type
     * @param minExpectedValue Optional minimum expected value
     * @param maxExpectedValue Optional maximum expected value
     * @param controlType Optional control type
     * @param isActive Whether the type is active
     * @return Result containing the created DeviceCatalogType or error
     */
    suspend fun createDeviceType(
        name: String,
        description: String?,
        categoryId: Short,
        defaultUnitId: Short?,
        dataType: String?,
        minExpectedValue: Double?,
        maxExpectedValue: Double?,
        controlType: String?,
        isActive: Boolean
    ): Result<DeviceCatalogType>

    /**
     * Updates an existing device type.
     * @param id The type ID to update
     * @param name Optional new name
     * @param description Optional new description
     * @param categoryId Optional new category ID
     * @param defaultUnitId Optional new default unit ID
     * @param dataType Optional new data type
     * @param minExpectedValue Optional new minimum expected value
     * @param maxExpectedValue Optional new maximum expected value
     * @param controlType Optional new control type
     * @param isActive Optional new active status
     * @return Result containing the updated DeviceCatalogType or error
     */
    suspend fun updateDeviceType(
        id: Short,
        name: String?,
        description: String?,
        categoryId: Short?,
        defaultUnitId: Short?,
        dataType: String?,
        minExpectedValue: Double?,
        maxExpectedValue: Double?,
        controlType: String?,
        isActive: Boolean?
    ): Result<DeviceCatalogType>

    /**
     * Deletes a device type.
     * @param id The type ID to delete
     * @return Result containing success or error
     */
    suspend fun deleteDeviceType(id: Short): Result<Unit>

    /**
     * Activates a device type.
     * @param id The type ID to activate
     * @return Result containing the updated DeviceCatalogType or error
     */
    suspend fun activateDeviceType(id: Short): Result<DeviceCatalogType>

    /**
     * Deactivates a device type.
     * @param id The type ID to deactivate
     * @return Result containing the updated DeviceCatalogType or error
     */
    suspend fun deactivateDeviceType(id: Short): Result<DeviceCatalogType>

    // ==================== DEVICE UNITS (READ ONLY) ====================

    /**
     * Fetches all device units from the catalog.
     * Note: Units do not support CRUD operations in the backend.
     * @return Result containing list of DeviceCatalogUnit or error
     */
    suspend fun getDeviceUnits(): Result<List<DeviceCatalogUnit>>

    // ==================== ALERT TYPES ====================

    /**
     * Fetches all alert types from the catalog.
     * @return Result containing list of AlertType or error
     */
    suspend fun getAlertTypes(): Result<List<AlertType>>

    /**
     * Creates a new alert type.
     * @param name The alert type name
     * @param description Optional description
     * @return Result containing the created AlertType or error
     */
    suspend fun createAlertType(name: String, description: String?): Result<AlertType>

    /**
     * Updates an existing alert type.
     * @param id The alert type ID to update
     * @param name Optional new name
     * @param description Optional new description
     * @return Result containing the updated AlertType or error
     */
    suspend fun updateAlertType(id: Short, name: String?, description: String?): Result<AlertType>

    /**
     * Deletes an alert type.
     * @param id The alert type ID to delete
     * @return Result containing success or error
     */
    suspend fun deleteAlertType(id: Short): Result<Unit>

    // ==================== ALERT SEVERITIES ====================

    /**
     * Fetches all alert severities from the catalog.
     * @return Result containing list of AlertSeverityCatalog or error
     */
    suspend fun getAlertSeverities(): Result<List<AlertSeverityCatalog>>

    /**
     * Creates a new alert severity.
     * @param name The severity name
     * @param level The severity level (lower = less severe)
     * @param description Optional description
     * @param color Optional color code (hex)
     * @param requiresAction Whether this severity requires user action
     * @param notificationDelayMinutes Delay before notification
     * @return Result containing the created AlertSeverityCatalog or error
     */
    suspend fun createAlertSeverity(
        name: String,
        level: Short,
        description: String?,
        color: String?,
        requiresAction: Boolean,
        notificationDelayMinutes: Int
    ): Result<AlertSeverityCatalog>

    /**
     * Updates an existing alert severity.
     * @param id The severity ID to update
     * @param name Optional new name
     * @param level Optional new level
     * @param description Optional new description
     * @param color Optional new color
     * @param requiresAction Optional new requires action flag
     * @param notificationDelayMinutes Optional new notification delay
     * @return Result containing the updated AlertSeverityCatalog or error
     */
    suspend fun updateAlertSeverity(
        id: Short,
        name: String?,
        level: Short?,
        description: String?,
        color: String?,
        requiresAction: Boolean?,
        notificationDelayMinutes: Int?
    ): Result<AlertSeverityCatalog>

    /**
     * Deletes an alert severity.
     * @param id The severity ID to delete
     * @return Result containing success or error
     */
    suspend fun deleteAlertSeverity(id: Short): Result<Unit>

    // ==================== PERIODS ====================

    /**
     * Fetches all periods from the catalog.
     * @return Result containing list of Period or error
     */
    suspend fun getPeriods(): Result<List<Period>>

    /**
     * Creates a new period.
     * @param name The period name
     * @return Result containing the created Period or error
     */
    suspend fun createPeriod(name: String): Result<Period>

    /**
     * Updates an existing period.
     * @param id The period ID to update
     * @param name The new period name
     * @return Result containing the updated Period or error
     */
    suspend fun updatePeriod(id: Short, name: String): Result<Period>

    /**
     * Deletes a period.
     * @param id The period ID to delete
     * @return Result containing success or error
     */
    suspend fun deletePeriod(id: Short): Result<Unit>
}
