package com.apptolast.greenhouse.admin.data.model

import kotlinx.serialization.Serializable

// ==================== PERIOD DTOs (Catalog) ====================

/**
 * Response DTO for Period from catalog API.
 * Periods define when a setting applies: DAY, NIGHT, or ALL (24h).
 */
@Serializable
data class PeriodResponse(
    val id: Short,
    val name: String
)

// ==================== SETTING DTOs ====================

/**
 * Response DTO for Setting from API.
 * Represents parameter threshold configuration for a sector.
 */
@Serializable
data class SettingResponse(
    val id: Long,
    val code: String,
    val sectorId: Long,
    val sectorCode: String? = null,
    val tenantId: Long,
    val parameterId: Short,
    val parameterName: String? = null,
    val actuatorStateId: Short? = null,
    val actuatorStateName: String? = null,
    val dataTypeId: Short? = null,
    val dataTypeName: String? = null,
    val value: String? = null,
    val description: String? = null,
    val isActive: Boolean = true,
    val createdAt: String,
    val updatedAt: String
)

/**
 * Request DTO for creating a new Setting.
 */
@Serializable
data class SettingCreateRequest(
    val sectorId: Long,
    val parameterId: Short,
    val actuatorStateId: Short? = null,
    val dataTypeId: Short? = null,
    val value: String? = null,
    val description: String? = null,
    val isActive: Boolean = true
)

/**
 * Request DTO for updating an existing Setting.
 * All fields are optional - only provided fields are updated.
 */
@Serializable
data class SettingUpdateRequest(
    val sectorId: Long? = null,
    val parameterId: Short? = null,
    val actuatorStateId: Short? = null,
    val dataTypeId: Short? = null,
    val value: String? = null,
    val description: String? = null,
    val isActive: Boolean? = null
)

// ==================== DOMAIN MODELS ====================

/**
 * Domain model for Period catalog entry.
 */
data class Period(
    val id: Short,
    val name: String
) {
    /**
     * Display name for the period (e.g., "Day", "Night", "All Day").
     */
    val displayName: String
        get() = when (name.uppercase()) {
            "DAY" -> "Day"
            "NIGHT" -> "Night"
            "ALL" -> "All Day"
            else -> name
        }
}

/**
 * Domain model for Setting entity.
 * Represents parameter threshold configuration for a sector.
 * Parameters reference device_types (e.g., TEMPERATURE, HUMIDITY).
 */
data class Setting(
    val id: Long,
    val code: String,
    val sectorId: Long,
    val sectorCode: String? = null,
    val tenantId: Long,
    val parameterId: Short,
    val parameterName: String?,
    val actuatorStateId: Short?,
    val actuatorStateName: String?,
    val dataTypeId: Short?,
    val dataTypeName: String?,
    val value: String?,
    val description: String?,
    val isActive: Boolean,
    val createdAt: String
) {
    /**
     * Returns the first two letters of the parameter name (uppercase) for avatar display.
     */
    val initials: String
        get() = parameterName?.take(2)?.uppercase() ?: "SE"

    /**
     * Display name for the setting (parameter name or fallback).
     */
    val displayName: String
        get() = parameterName ?: "Parameter $parameterId"

    /**
     * Formatted display of the value.
     */
    val valueDisplay: String
        get() = value ?: "-"

    /**
     * Display name for the actuator state.
     */
    val actuatorStateDisplayName: String
        get() = actuatorStateName ?: (actuatorStateId?.let { "State $it" } ?: "-")

    /**
     * Display name for the data type.
     */
    val dataTypeDisplayName: String
        get() = dataTypeName ?: (dataTypeId?.let { "Type $it" } ?: "-")
}

// ==================== EXTENSION FUNCTIONS ====================

/**
 * Converts PeriodResponse DTO to Period domain model.
 */
fun PeriodResponse.toDomain() = Period(
    id = id,
    name = name
)

/**
 * Converts SettingResponse DTO to Setting domain model.
 */
fun SettingResponse.toDomain() = Setting(
    id = id,
    code = code,
    sectorId = sectorId,
    sectorCode = sectorCode,
    tenantId = tenantId,
    parameterId = parameterId,
    parameterName = parameterName,
    actuatorStateId = actuatorStateId,
    actuatorStateName = actuatorStateName,
    dataTypeId = dataTypeId,
    dataTypeName = dataTypeName,
    value = value,
    description = description,
    isActive = isActive,
    createdAt = createdAt
)

// ==================== PERIOD CATALOG REQUEST DTOs ====================

/**
 * Request DTO for creating a Period.
 * Note: ID is auto-generated by the backend.
 */
@Serializable
data class PeriodCreateRequest(
    val name: String
)

/**
 * Request DTO for updating a Period.
 */
@Serializable
data class PeriodUpdateRequest(
    val name: String? = null
)

// ==================== DATA TYPE DTOs (Catalog) ====================

/**
 * Response DTO for DataType from catalog API.
 * Data types define the kind of data associated with setpoints (consignas).
 */
@Serializable
data class DataTypeResponse(
    val id: Short,
    val name: String,
    val description: String? = null
)

/**
 * Request DTO for creating a DataType.
 */
@Serializable
data class DataTypeCreateRequest(
    val name: String,
    val description: String? = null
)

/**
 * Request DTO for updating a DataType.
 */
@Serializable
data class DataTypeUpdateRequest(
    val name: String? = null,
    val description: String? = null
)

/**
 * Domain model for DataType catalog entry.
 */
data class DataType(
    val id: Short,
    val name: String,
    val description: String?
)

/**
 * Converts DataTypeResponse DTO to DataType domain model.
 */
fun DataTypeResponse.toDomain() = DataType(
    id = id,
    name = name,
    description = description
)
